{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "0fdb9405-e2fe-4486-92ef-de8bf27e41e6",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "from PIL import Image\n",
    "\n",
    "st.set_page_config(\n",
    "page_title=\"Simulador Ovocitos ⇄ Embriones | Equipo Juana Crespo\",\n",
    "page_icon=\"👶\",\n",
    "layout=\"centered\",\n",
    ")\n",
    "\n",
    "COLOR_PRINCIPAL = \"#C2A27B\" # beige Juana Crespo\n",
    "COLOR_TEXTO = \"#FFFFFF\"\n",
    "COLOR_FONDO = \"#000000\"\n",
    "\n",
    "st.markdown(f\"\"\"\n",
    "<style>\n",
    "body {{\n",
    "background-color: {COLOR_FONDO};\n",
    "color: {COLOR_TEXTO};\n",
    "}}\n",
    ".stApp {{\n",
    "background-color: {COLOR_FONDO};\n",
    "}}\n",
    ".title {{\n",
    "text-align: center;\n",
    "color: {COLOR_TEXTO};\n",
    "font-size: 36px;\n",
    "font-weight: bold;\n",
    "}}\n",
    ".note {{\n",
    "color: {COLOR_PRINCIPAL};\n",
    "font-size: 13px;\n",
    "text-align: center;\n",
    "margin-top: 20px;\n",
    "}}\n",
    ".stSlider > div, .stRadio > label, .stSelectbox label {{\n",
    "color: {COLOR_TEXTO};\n",
    "}}\n",
    "</style>\n",
    "\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "\n",
    "st.markdown(\"<div class='title'>Simulador Ovocitos ⇄ Embriones</div>\", unsafe_allow_html=True)\n",
    "\n",
    "data = {\n",
    "\"Edad\": [\"Hasta 34\", 35, 36, 37, 38, 39, 40, 41, 42, 43, \"44 o más\"],\n",
    "\"% Fecundados 2PN/Ovocitos Obtenidos\": [0.65, 0.64, 0.66, 0.65, 0.64, 0.64, 0.63, 0.63, 0.62, 0.63, 0.61],\n",
    "\"% Embriones Útiles/Fecundados 2PN\": [0.56, 0.57, 0.56, 0.57, 0.55, 0.55, 0.51, 0.48, 0.42, 0.37, 0.29],\n",
    "\"Embriones Transferibles/Embriones Útiles\": [0.64, 0.57, 0.56, 0.52, 0.45, 0.40, 0.34, 0.26, 0.21, 0.14, 0.07]\n",
    "}\n",
    "\n",
    "df = pd.DataFrame(data)\n",
    "\n",
    "\n",
    "\n",
    "modo = st.radio(\n",
    "\"Selecciona el modo de simulación:\",\n",
    "[\"De ovocitos a embriones\", \"De embriones a ovocitos\"]\n",
    ")\n",
    "\n",
    "edad = st.selectbox(\"Selecciona la edad de la paciente:\", df[\"Edad\"])\n",
    "fila = df[df[\"Edad\"] == edad].iloc[0]\n",
    "\n",
    "\n",
    "if modo == \"De ovocitos a embriones\":\n",
    "    ovocitos = st.number_input(\"Introduce el número de ovocitos esperados/obtenidos:\", min_value=1, value=10, step=1)\n",
    "    fecundados = ovocitos * fila[\"% Fecundados 2PN/Ovocitos Obtenidos\"]\n",
    "    utiles = fecundados * fila[\"% Embriones Útiles/Fecundados 2PN\"]\n",
    "    transferibles = utiles * fila[\"Embriones Transferibles/Embriones Útiles\"]\n",
    "\n",
    "    st.markdown(f\"### Resultados estimados para {ovocitos} ovocitos:\")\n",
    "    st.write(f\"**Fecundados (2PN):** {fecundados:.1f}\")\n",
    "    st.write(f\"**Embriones útiles:** {utiles:.1f}\")\n",
    "    st.write(f\"**Embriones transferibles:** {transferibles:.1f}\")\n",
    "\n",
    "else:\n",
    "    tipo_objetivo = st.radio(\n",
    "    \"Selecciona el tipo de embriones que vas a introducir:\",\n",
    "    [\"Embriones transferibles\", \"Embriones útiles\"]\n",
    "    )\n",
    "    if tipo_objetivo == \"Embriones transferibles\":\n",
    "        transferibles_deseados = st.number_input(\"Introduce el número de embriones transferibles deseados:\", min_value=1, value=2, step=1)\n",
    "        \n",
    "        utiles_necesarios = transferibles_deseados / fila[\"Embriones Transferibles/Embriones Útiles\"]\n",
    "        fecundados_necesarios = utiles_necesarios / fila[\"% Embriones Útiles/Fecundados 2PN\"]\n",
    "        ovocitos_necesarios = fecundados_necesarios / fila[\"% Fecundados 2PN/Ovocitos Obtenidos\"]\n",
    "        \n",
    "        st.markdown(f\"### Estimación para obtener {transferibles_deseados} embriones transferibles:\")\n",
    "        st.write(f\"**Embriones útiles necesarios:** {utiles_necesarios:.1f}\")\n",
    "        st.write(f\"**Fecundados (2PN) necesarios:** {fecundados_necesarios:.1f}\")\n",
    "        st.write(f\"**Ovocitos necesarios:** {ovocitos_necesarios:.1f}\")\n",
    "\n",
    "\n",
    "    else:\n",
    "        utiles_deseados = st.number_input(\"Introduce el número de embriones útiles deseados:\", min_value=1, value=3, step=1)\n",
    "        \n",
    "        fecundados_necesarios = utiles_deseados / fila[\"% Embriones Útiles/Fecundados 2PN\"]\n",
    "        ovocitos_necesarios = fecundados_necesarios / fila[\"% Fecundados 2PN/Ovocitos Obtenidos\"]\n",
    "        transferibles_estimados = utiles_deseados * fila[\"Embriones Transferibles/Embriones Útiles\"]\n",
    "        \n",
    "        st.markdown(f\"### Estimación para obtener {utiles_deseados} embriones útiles:\")\n",
    "        st.write(f\"**Fecundados (2PN) necesarios:** {fecundados_necesarios:.1f}\")\n",
    "        st.write(f\"**Ovocitos necesarios:** {ovocitos_necesarios:.1f}\")\n",
    "        st.write(f\"**Embriones transferibles estimados:** {transferibles_estimados:.1f}\")\n",
    "        \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "56b71d1b-ddcf-4a5b-accd-6345fde395ee",
   "metadata": {},
   "outputs": [],
   "source": [
    "st.markdown(\"<div class='note'>Estimaciones basadas en probabilidades históricas; resultados individuales pueden variar.</div>\", unsafe_allow_html=True)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
